# Based on Absinthe's CI: https://github.com/absinthe-graphql/absinthe/blob/master/.github/workflows/elixir.yml
name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        elixir:
          - "1.13"
          - "1.14"
          - "1.15"
        otp:
          - "24"
          - "25"
          - "26"
        include:
          - elixir: "1.15"
            otp: "26"
            format: true
        exclude:
          - otp: 26
            elixir: 1.13
          - otp: 26
            elixir: 1.14

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
        	use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set up Elixir
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore deps cache
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}-${{ github.sha }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - name: Install package dependencies
        run: mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted
        if: ${{ matrix.format }}

      - name: Run unit tests
        run: |
          mix clean
          mix test

      - name: Run unit tests with persistent_term backend
        run: |
          mix clean
          mix test

      - name: Cache/uncache PLTs
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: |
            priv/plts
          key: "v1-${{ runner.os }}-\
                erlang-${{ matrix.otp }}-\
                elixir-${{ matrix.elixir }}-\
                ${{ hashFiles('mix.lock') }}"

      - name: Run Dialyzer
        run: mix dialyzer